### ISSUE TITLE
Boost regex and Cyrillic

### ISSUE THREAD

**Issue by ProgerXP** [ProgerXP/Notepad2e#162]
Boost regex in Perl-compatible mode has `\U` escape sequence to convert characters to upper case. Example: doc `abc`, replace from `^.` to `\U$0` - result `Abc`.

However, this doesn't work for Cyrillic symbols (doc `фыв` = `фыв`). Boost regex is normally fully Unicode-aware, do you know if `\U` is hardcoded to only work on Latin symbols or there's some flag that enables it for all Unicode ranges? Notepad++ has the same issue so it seems to be the first case.

**Comment by cshnik** [comment]
This is a result of ``towupper`` limitation which is used in the current boost regex build.
https://stackoverflow.com/questions/41538726/c-towupper-doesnt-convert-certain-characters#41538912:
> Implementations of towupper are not required by the C++ standard to perform Unicode case conversions. Even if wide strings are Unicode strings. Even in cases where one lower-case codepoint mapps to one upper-case one.
> 
> Furthermore, towupper is incapable of performing proper Unicode case conversion, even if the implementation supported it. Case conversion can actually change the number of codepoints in a Unicode character sequence. And towupper is incapable of doing that.
> 
> You cannot rely on the C++ standard library for dealing with Unicode matters of this sort. You'll need to move to a dedicated Unicode library like ICU.

Boost regex library should be recompiled using ICU (https://www.boost.org/doc/libs/1_67_0/libs/regex/doc/html/boost_regex/ref/non_std_strings/icu.html) to support such a functionality. I'll continue my investigation on this topic.

**Comment by cshnik** [comment]
Building a boost regex statically linked to ICU (to get rid of external DLL modules) will cause a significant growth of Notepad2e binary size, e.g. >10 MB instead of current ~2MB. Is build binary size is a very critical metric for the project?

**Comment by mva1985** [comment]
The size is not an issue for me either

**Comment by cshnik** [comment]
Test build with ICU: [Notepad2e-ICU.zip](https://github.com/ProgerXP/Notepad2e/raw/03070231ffa1f77e20d9b61f4b85f2299435079d/bin/Notepad2e-ICU.zip)
At this point it uses external DLLs. Rebuilding of Notepad2e with statically linked ICU requires additional work and will result with ~30MB binary size. Do we actually need a single binary file for ICU build (with no external DLLs) or current option is OK?

**Comment by ProgerXP** [comment]
> Do we actually need a single binary file for ICU build (with no external DLLs) or current option is OK?

No, we need a DLL-less version. Many people are using this fork to replace Windows' Notepad and it's way more convenient when it's a single EXE file.

That said, it now fails without v140 runtime - is it essential?

**Comment by cshnik** [comment]
All required changes are in the ``Boost_regex_and_Cyrillic_#162`` branch.

**Comment by ProgerXP** [comment]
> All required changes are in the Boost_regex_and_Cyrillic_#162 branch.

1. On a Cyrillic UTF-8 document, Replace With works correctly.
2. On an ANSI document (which can display Cyrillic), Replace With corrupts the text.
3. What about a single-binary build, is it possible?
4. What about v140 runtime?

**Comment by cshnik** [comment]
>2. On an ANSI document (which can display Cyrillic), Replace With corrupts the text.

Correct. ICU is a unicode library. Implemented functionality affects only unicode files. For ANSI files specific ANSI document iterator (used for reading characters) is called and ICU get never involved in the regex processing.

> 3. What about a single-binary build, is it possible?

Single-binary test build was already uploaded [here](https://github.com/ProgerXP/Notepad2e/blob/Boost_regex_and_Cyrillic_%23162/bin/Notepad2e-static-ICU.zip?raw=true).

> 4. What about v140 runtime?

It may take few hours to rebuild ICU, boost, Notepad2e with v140 runtime.

**Comment by ProgerXP** [comment]
> Single-binary test build was already uploaded here.

Any Replace operation such as Search String `фу` (any Replace String, e.g. blank) on any document (e.g. `фуцк`) causes 100% CPU load and a frozen process.

**Comment by ProgerXP** [comment]
> All required changes are in the Boost_regex_and_Cyrillic_#162 branch.

Is it possible to merge the branch so that we have a single solution file and be able to build both single-binary ICU version (20+ MiB) and regular non-ICU version (2 MiB) from that single solution? Or are there incompatible changes?

**Comment by cshnik** [comment]
> Any Replace operation such as Search String фу (any Replace String, e.g. blank) on any document (e.g. фуцк) causes 100% CPU load and a frozen process.
Update: on an ANSI document. If ICU isn't getting called for non-Unicode charsets, why the freeze?
Update: it only happens if Search String contains a Cyrillic symbol.

There is a bug in the ICU build: input text is always treated as UTF8 which is the cause for a hang when working with ANSI document.
I made additional research to find out if there is a direct way to utilize regex for non-unicode strings when using boost regex compiled with ICU and finally concluded this is technically impossible. The point is: when using regular boost regex there are at least 2 available implementations (for unicode/non-unicode strings) while boost with ICU implements interface for unicode strings only.
There are 2 ways to address this issue:
1. Disable regex for non-unicode files in the ICU build. Fast and safe way.
2. Implement intermediate conversion of non-unicode strings to utf8 when calling regex in the ICU build. I.e. to call ICU regex properly we should convert source strings to unicode in the runtime, this requires additional handling for the string conversion and position/length adjustment. This work will heavily affect the internals of BoostRegExSearch and Ansi/UTF8/UTF32DocumentIterator modules and will take some time.

Please confirm the solution we should implement to fix ANSI issue.

> Is it possible to merge the branch so that we have a single solution file and be able to build both single-binary ICU version (20+ MiB) and regular non-ICU version (2 MiB) from that single solution? Or are there incompatible changes?

Additional ICU configurations (Debug ICU/Release ICU) were added to original solution to make it possible to compile regular and ICU builds on the same code base.

**Comment by ProgerXP** [comment]
>>> That said, it now fails without v140 runtime - is it essential?

>> It may take few hours to rebuild ICU, boost, Notepad2e with v140 runtime.

> Additional ICU configurations (Debug ICU/Release ICU) were added to original solution to make it possible to compile regular and ICU builds on the same code base.

Will it build without requiring v140 runtime? Ideally we should keep the original requirements of Notepad2.

**Comment by cshnik** [comment]
> Let's do this: in an ICU build, if user tries to Find or Replace with Regexp mode enabled and the buffer is not Unicode - display a message with two choices and the "remember" checkbox (standard message boxes displayed by Notepad e.g. when opening a large file):
...
> "No" cancels the Find/Replace operation.

Done. Please check test ICU build here: [Notepad2e.exe.zip](https://github.com/ProgerXP/Notepad2e/blob/Boost_regex_and_Cyrillic_%23162/bin/ICU/Notepad2e.exe.zip)

> Regexps should work for any kind of Unicode buffers - UTF-8, UCS, etc. etc. right?

Yes, it works for unicode files.

> Will it build without requiring v140 runtime? Ideally we should keep the original requirements of Notepad2.

There is a section in the Notepad2e.vcxproj which describes platform toolset required for exact VisualStudio version:
```
 <PropertyGroup Label="Configuration">
    <ConfigurationType>Application</ConfigurationType>
    <CharacterSet>Unicode</CharacterSet>
    <PlatformToolset Condition="'$(VisualStudioVersion)' == '15.0'">v141_xp</PlatformToolset>
    <PlatformToolset Condition="'$(VisualStudioVersion)' == '14.0'">v140_xp</PlatformToolset>
  </PropertyGroup>
```
VS2015 uses "Visual Studio 2015 - Windows XP (v140_xp)" toolset, VS2017 uses "Visual Studio 2017 - Windows XP (v141_xp)" toolset. These are different but both are used for building application for Windows XP. In this case application is ready to be launched on target OS without some specific runtime installed. Please check this article for additional details: [Configuring Programs for Windows XP](https://docs.microsoft.com/en-us/cpp/build/configuring-programs-for-windows-xp?view=vs-2017)

**Comment by ProgerXP** [comment]
1. I am unable to compile the `Release ICU|x86` build configuration:

```
boost_1_68_0\boost\regex\icu.hpp(23, 0): error C1083: Cannot open include file: 'unicode/utypes.h': No such file or directory (compiling source file scintilla\boostregex\BoostRegExSearch.cxx)
```

2. When trying to compile tests from this branch, I get:

```
StringRecoding.obj error LNK2019: unresolved external symbol _n2e_IsUnicodeEncodingMode referenced in function _Recode_ProcessDataPortion
StrToHex.obj error LNK2001: unresolved external symbol _n2e_IsUnicodeEncodingMode
```

3. Let's add an indication to app title when it's an ICU build. By default, leave current `Notepad 2e` text. In an ICU build, let window title be `Notepad 2e-ICU` (e.g. `Untitled - Notepad 2e-ICU`). Also add `-ICU` to the first line in the About box and to the box' title (`Notepad 2e-ICU | Based on ...`).

Maybe we should similarly change other strings like VERSION info (File Description, etc.) - if that's not too hard.

4. Do you know what other benefits does ICU regexp provide, other than correct `\U \u \L \l` handling? Even in non-ICU build, `\w` ("word" symbol) and `\pL` ("Letter" as defined by the Unicode standard) work correctly on Cyrillic symbols (I'd think that if `\U` doesn't recognize `ф` than neither `\w` nor `\pL` would but they do recognize it). Do you know why?

**Comment by cshnik** [comment]
> 1. I am unable to compile the Release ICU|x86 build configuration:

Fixed project configurations. Please make sure ICU_ROOT environment variable is properly set as stated in the [ICUBuild.md](https://github.com/ProgerXP/Notepad2e/blob/Boost_regex_and_Cyrillic_%23162/doc/ICUBuild.md)

> 2. When trying to compile tests from this branch, I get: ...

Fixed.

> 3. Let's add an indication to app title when it's an ICU build. By default, leave current `Notepad 2e` text. In an ICU build, let window title be `Notepad 2e-ICU` (e.g. `Untitled - Notepad 2e-ICU`). Also add `-ICU` to the first line in the About box and to the box' title (`Notepad 2e-ICU | Based on ...`).

Done. However output binary name remained the same (Notepad2.exe).
BTW, please confirm if we need to maintain x64 ICU builds.

>4. Do you know what other benefits does ICU regexp provide, other than correct `\U \u \L \l` handling? 

N/A. But any other locale specific operations should be properly handled. Here are some notes regarding the [ICU engine](https://www-01.ibm.com/software/globalization/icu/) features:
>* Text: Unicode text handling, full character properties and character set conversions (500 + code pages)
>* Analysis: Unicode regular expressions; full Unicode sets; character, word and line boundaries
>* Comparison: language sensitive collation and searching
>* Transformations: normalization, upper/lowercase, script transliterations (50 + pairs)
>* Locales: comprehensive data (230 +) & resource bundle architecture
>* Complex Text Layout: Arabic, Hebrew, Indic and Thai

> 4> Even in non-ICU build, `\w` ("word" symbol) and `\pL` ("Letter" as defined by the Unicode standard) work correctly on Cyrillic symbols (I'd think that if `\U` doesn't recognize `ф` than neither `\w` nor `\pL` would but they do recognize it). Do you know why?

The actual reason is that `\U` operation was not properly handled when using common regex. When running replace operation Notepad2e stated `"1 occurences of the specified text have been replaced"` but the text was not actually changed since `\U` for cyrillic chars is not supported.

Here is the test ICU build with recent changes: [Notepad2e.zip](https://github.com/ProgerXP/Notepad2e/blob/Boost_regex_and_Cyrillic_%23162/bin/Win32/Release%20ICU/Notepad2e.zip)

**Comment by ProgerXP** [comment]
>> Please make sure ICU_ROOT environment variable is properly set as stated in the ICUBuild.md

> Patch ICU file icu4c\source\common\putil.cpp:

Your README says:

```
#if U_PLATFORM_HAS_WINUWP_API == 0
    // If not a Universal Windows App, we'll need user default language.
    // Vista and above should use Locale Names instead of LCIDs
    int length = GetUserDefaultLocaleName(windowsLocale, UPRV_LENGTHOF(windowsLocale));
#else
```

But what I see is:

```
#       if U_PLATFORM_HAS_WINUWP_API == 0  // Windows UWP does not support getenv
        path=getenv("ICU_DATA");
#       endif
```

Do I need a specific ICU version? I got one from GitHub: https://github.com/unicode-org/icu => Download ZIP.

>  BTW, please confirm if we need to maintain x64 ICU builds.

Is there any problem with them? If it's about you compiling executables, it's not an issue - I've set up a server for automatic compilation (just need a few other things like #195).

**Comment by ProgerXP** [comment]
> Patch icu4c\runConfigureICU file:

I only see this file: icu4c/source/runConfigureICU

> VI. Patch boost source code

Does this need to be done separately for ICU and non-ICU builds? I mean, do I need to have 2 separate Boost roots if I want to compile both versions? If so, how do I do it - there's only one BOOST_ROOT variable.

> The actual reason is that \U operation was not properly handled when using common regex. 

What I mean is that it's strange that `\U` is not handled properly while \pL and \w (which also require knowledge about Unicode properties) are handled even without ICU. Is this a bug in Boost or...?

**Comment by cshnik** [comment]
> Do I need a specific ICU version? I got one from GitHub: https://github.com/unicode-org/icu => Download ZIP.

I have updated ICUBuild.md and stated [exact](https://github.com/unicode-org/icu/archive/55ecf77306e2f73ddced8d8e6deb510dfbffd94e.zip) ICU version/commit which 100% can be patched for XP.
I've tried to patch and compile the most recent ICU sources and found some other problems with it. It looks like there are new requirements/dependencies for CygWin and I was unable to build it. I assume at this point we can stay on this "outdated" ICU version from 09/05/2018.

>>  BTW, please confirm if we need to maintain x64 ICU builds.

> Is there any problem with them? If it's about you compiling executables, it's not an issue - I've set up a server for automatic compilation (just need a few other things like #195).

I've never tried to compile x64 ICU, it may take some time. #195 is upcoming.

> I only see this file: icu4c/source/runConfigureICU

Fixed path in the document.

> Does this need to be done separately for ICU and non-ICU builds? I mean, do I need to have 2 separate Boost roots if I want to compile both versions? If so, how do I do it - there's only one BOOST_ROOT variable.

Yes, boost should be compiled separately for ICU/non-ICU builds. Updated solution have separate environment variables: %BOOST_ROOT% and %BOOST_ROOT_ICU%.

> What I mean is that it's strange that \U is not handled properly while \pL and \w (which also require knowledge about Unicode properties) are handled even without ICU. Is this a bug in Boost or...?

To my mind, it is simple to check character's group (upper/lower char or digit) since there are known ranges in charset, while implementation of transformation requires complete mapping for every character in every charset.

**Comment by ProgerXP** [comment]
> I assume at this point we can stay on this "outdated" ICU version from 09/05/2018.

Most certainly.

> 2. Install Cygwin, install next packages: bash, GNU make, ar, ranlib

How to install ar and ranlib? In cygwin setup (GUI), when I "search" for ar I get dozens of items (but none matching "ar" exactly); for ranlib - I get nothing.

> VII. Build boost regex
> 3. Run command:

The command contains references to C:\icu. Is it possible to use %ICU_ROOT% in this command in case the path is different (it's different on my system so I have to manually rewrite the command)? Are env vars supported here?

> `cd C:\icu\icu4c\source`

This can be `cd %ICU_ROOT%\icu4c\source`.

> I've never tried to compile x64 ICU, it may take some time. 

I can try to compile ICU and Boost for x64. What should I do compared to normal ICUBuild.md?

I have compiled ICU according to your instructions (I assume it's for x86). However, Boost compilation fails at step 3 (running **b2** after bootstrap.bat):

```
boost/regex/icu.hpp(23): fatal error C1083: Cannot open
include file: 'unicode/utypes.h': No such file or directory

    call "bin.v2\standalone\msvc\msvc-14.1\msvc-setup.bat"  >nul
 cl /Zm800 -nologo @"bin.v2\libs\regex\build\msvc-14.1\debug\link-static\runtime-link-static\threading-multi\icu.obj.rsp"
```

> To my mind, it is simple to check character's group (upper/lower char or digit) since there are known ranges in charset, while implementation of transformation requires complete mapping for every character in every charset.

Indeed, must be the reason.

**Comment by ProgerXP** [comment]
> However, Boost compilation fails at step 3 (running b2 after bootstrap.bat):

Nevermind, solved by reopening the command prompt and recompiling Boost. 

> VIII. Create ICU regex static library

Can you correct formatting of the command in point 4?

I have successfully compiled Release ICU|x86 and got a working build. I can try x64 now for the sake of completeness.

**Comment by cshnik** [comment]
> How to install ar and ranlib?

Removed these excess items from the requirements list.

> The command contains references to C:\icu. Is it possible to use %ICU_ROOT% in this command in case the path is different (it's different on my system so I have to manually rewrite the command)? Are env vars supported here?

Improved bash command to rely on %ICU_ROOT% only:
`
C:\icu\icu4c\source> bash -exec "ICU_ROOT_UNIX=$(cygpath -u ${ICU_ROOT});bash runConfigureICU Cygwin/MSVC -prefix=${ICU_ROOT_UNIX} --enable-static --disable-shared --enable-release --disable-debug"
`

>> `cd C:\icu\icu4c\source`
>This can be `cd %ICU_ROOT%\icu4c\source`.

Changed to `cd %ICU_ROOT%\..\icu4c\source`.

> Can you correct formatting of the command in point 4?

Fixed.

> I can try to compile ICU and Boost for x64. What should I do compared to normal ICUBuild.md?
1. Patch `icu4c\source\config\mh-cygwin-msvc`:
`-subsystem:console,5.01`
replace with:
`-subsystem:console,5.02`
2. Rebuild ICU using x64 Native tools (command line is the same as for x86).
3. Rebuild boost:
`> b2 address-model=64 architecture=x86 link=static runtime-link=static --with-regex --stagedir=stage/x64 define=_USING_V110_SDK71_=1 define=U_STATIC_IMPLEMENTATION=1 -sHAVE_ICU=1 -sICU_PATH=%ICU_ROOT% -sICU_LINK="/LIBPATH:%ICU_ROOT%\lib sicuucd.lib sicudtd.lib sicuind.lib sicuiod.lib sicutud.lib advapi32.lib" --disable-debug --enable-release`
4. Merge lib files:
`> lib /OUT:icuregex64.lib libboost_regex-vc141-mt-s-x64-1_68.lib sicudt.lib sicuin.lib sicuuc.lib`

Required steps are already listed in the [ICUBuild.md](https://github.com/ProgerXP/Notepad2e/blob/Boost_regex_and_Cyrillic_%23162/doc/ICUBuild.md).

BTW I have a changed some paths/actions in ICUBuild document to conform output folders the target configuration (x86/x64) and to make build process clear and simple.

> I've set up a server for automatic compilation (just need a few other things like #195).

Please confirm if we should fix #195 in the `Boost_regex_and_Cyrillic_#162`-branch which is a placeholder for all the changes for #162 issue.

**Comment by ProgerXP** [comment]
>> How to install ar and ranlib?

> Removed these excess items from the requirements list.

You did? I still see both in the README.

> IV. Patch ICU source code

Point 3 now includes two sections:

```
    For x86:
...
    For x64:
...
```

Do I have to re-patch this file whenever I want to compile for x86 or for x64? There's no way to have a non-conflicting change here?

**Comment by ProgerXP** [comment]
> Do I have to re-patch this file whenever I want to compile for x86 or for x64? There's no way to have a non-conflicting change here?

Or is it a one-time operation: 1) I patch the files, 2) compile ICU and Boost, 3) copy the libraries.

Now with the libraries I can build Notepad 2e as many times as necessary, right?

**Comment by ProgerXP** [comment]
We're going to remove the compiled exe from the repository after this issue is closed. Therefore please:

1. Remove bin/Notepad2e.exe
1. Remove bin/Win32/Release ICU/Notepad2e.zip
1. Remove icuregex.lib.zip (we don't need it right?)
2. Change Release|x86 so that compiled result goes into bin/Win32/Release/Notepad2e.exe

Am I correct that all other build configurations:

- Release|x64 outputs result to bin/x64/Release/Notepad2e.exe
- Release ICU|x64 outputs result to bin/x64/Release ICU/Notepad2e.exe
- Release ICU|x86 outputs result to bin/Win32/Release ICU/Notepad2e.exe?

**Comment by ProgerXP** [comment]
I have compiled all 3 configurations except Release ICU|x64 - it gives me 25 unresolved external symbols. Any idea why?

**Comment by ProgerXP** [comment]
I can't rebuild Bosot for x64, is there a mistake in the command line?

```
fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'x86'
```

Do note that in the Readme:

```
C:\Program Files\boost\boost_1_68_0_icu> b2 address-model=64 architecture=x86 ...
```

...this `architecture=x86` part for x64 section, is this really correct?

**Comment by ProgerXP** [comment]
I figured it. One has to remove bin.v2\libs\regex\build directory before running b2, else it seems to reuse binaries from the previous build run (in my case it was x86) and fails.

I finally have all 4 configurations building. Merge the branch please.

> Alternatively, we can utilize some x64 specific conditions to implement x86/x64 compatible patch. 

No need for this.

**Comment by cshnik** [comment]
> Merge the branch please.

Done.

**Comment by ProgerXP** [comment]
The branch was fully merged, right? In this case it should be removed from the repository.
